### PR TITLE
Refactor to use nextcloud/vm install script

### LINKED ISSUE #1: Project is out of date, use vm script instead?
# Problem

This repo is great! It was wonderful to see the install steps in simplest form.

However, there have been many updates to nextcloud, so this repo is out of date.

# Proposed Resolution

I made my own attempts to just clone this repo and update to v17, but ran into some issues related to the vm not being able to find packages. So, I took a look at https://github.com/nextcloud/vm and https://docs.nextcloud.com/server/17/admin_manual/installation/source_installation.html and decided to try it. It was very easy to use!

So, a suggestion here to keep this up to date would be to replace the install shell script for provisioning with `nextcloud_install_production.sh`.

### PR DESCRIPTION
**Pull request by josephdpurcell**
Fixes https://github.com/gjgd/vagrant-nextcloud/issues/1

### CODE REVIEW

**Comment by josephdpurcell** [comment]
I tested this locally and it worked great!

**Comment by gjgd** [comment]
Thanks for the updating the script!

I tried running `vagrant up` locally but it does not work. It hangs and never finishes.
Im on MacOS Mojave v10.14.6 using vagrant v2.1.2

As far as I can see, the install breaks between setting up the apache server and the nextcloud server because I see the default apache page on the localhost url

Can you try running:
```
vagrant destroy
vagrant up
```
and confirm that it works for you?

**Comment by josephdpurcell** [comment]
Here's output:

```
$ uname -a
Linux mylaptop 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ vagrant --version
Vagrant 2.1.2
$ VBoxManage --version
5.1.38r122592
$ vagrant plugin list
vagrant-auto_network (1.0.3)
vagrant-bindfs (1.1.0)
vagrant-hostsupdater (1.1.1.160)
vagrant-vbguest (0.15.2)
$ git log -1
commit 3e62f81f33e24bc54dee6486686003be09306fe9
Author: Joseph D. Purcell <josephdpurcell@gmail.com>
Date:   Tue Dec 3 22:19:53 2019 -0500

    Update README
$ vagrant status
Current machine states:

default                   not created (virtualbox)

The environment has not yet been created. Run `vagrant up` to
create the environment. If a machine is not created, only the
default provider will be shown. So if a provider is not listed,
then the machine is not created for that environment.
$ vagrant up
```

Lots of output, and the terminal gets goofy:

Screenshot from 2019-12-04 09-54-19

But, I can login fine:

Screenshot from 2019-12-04 09-55-28

Vagrant usually doesn't care about the operating system, so maybe its plugins or VirtualBox version differences?

**Comment by gjgd** [comment]
This is my config 
```
➜ uname -a
Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

➜ vagrant --version
Vagrant 2.1.2

➜ VBoxManage --version
5.2.14r123301

➜ vagrant plugin list
vagrant-auto_network (1.0.3)
vagrant-bindfs (1.1.4)
vagrant-hostsupdater (1.1.1.160)
vagrant-vbguest (0.22.0)
```

And this is the error I get:

```
default: /dev/fd/63: line 178: 15111 Segmentation fault      (core dumped) whiptail --title "Nextcloud VM - T&M Hansson IT - $(date +"%Y")" --msgbox "${PROMPT}" "$WT_HEIGHT" "$WT_WIDTH"
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

When I ssh into the vm and I try to run `yes no | sudo bash nextcloud_install_production.sh` I get this 
Screenshot 2019-12-04 at 23 57 16

This is what is causing the error above ^

**Comment by josephdpurcell** [comment]
It worked for me on my mac as well:

```
$ git clone git@github.com:josephdpurcell/vagrant-nextcloud.git
$ cd vagrant-nextcloud
$ git checkout feature/use-vm-repo
$ vagrant up
```

Lots of output, then a sort of broken terminal like my Linux machine:

Screen Shot 2019-12-04 at 7 47 22 PM

And I can login successfully:

Screen Shot 2019-12-04 at 7 47 46 PM

Here are specs for this machine:

```
$  uname -a
Darwin joep-mac.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
$ vagrant --version
Vagrant 2.2.0
$ VBoxManage --version
5.2.20r125813
$ vagrant plugin list
vagrant-auto_network (1.0.3, global)
  - Version Constraint: > 0
vagrant-bindfs (1.1.0, global)
  - Version Constraint: > 0
vagrant-hostsupdater (1.1.1.160, global)
  - Version Constraint: > 0
vagrant-vbguest (0.17.2, global)
  - Version Constraint: > 0
```

Any thoughts on why it  works on 2 of my machines but not yours? What is different? What am I not comparing?

**Comment by gjgd** [comment]
I ran it with no other program running and it worked so I guess it was a RAM issue. Merging this, thanks for the contribution! That script is much simpler

**Comment by josephdpurcell** [comment]
Whew, I'm relieved! I was hoping it wasn't going to be a rabbit hole of gremlins.

YAY! Go open source!!!

**Pull request merged**
